server:
  port: 5050
  tomcat:
    basedir: F:\tomcat_project\temp

spring:
  application:
    name: demo-up_download-consumer


dubbo:
  application:
    name: ${spring.application.name}
  registry:
    #    address: nacos://127.0.0.1:5545
    address: nacos://10.10.27.86:8858
  #    address: nacos://192.168.253.128:8848
  protocol:
    port: 20883
    name: dubbo
  consumer:
    check: false
    timeout: 30000

