server:
  port: 5058


spring:
  application:
    name: demo-up_downlaod-provider

dubbo:
  application:
    name: ${spring.application.name}
  registry:
#    address: nacos://127.0.0.1:5545
    address: nacos://10.10.27.86:8858
#    address: nacos://192.168.253.128:8848
  protocols:
    dubbo:
        port: 20880
        name: dubbo
        payload: 1382327000
    hessian:
        port: 20881
        name: hessian
        server: tomcat
